{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}
{% set release = '.'.join(version.split('.')[:2]) %}

package:
  name: q2-health-index
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - numpy
    - pandas
    - qiime2 {{ release }}.*
    - q2-feature-table {{ release }}.*

test:
  imports:
    - q2_health_index
    - qiime2.plugins.health_index

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD